// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: domain/teams/messages.proto

package teams

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateTeam) Reset() {
	*x = CreateTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_teams_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeam) ProtoMessage() {}

func (x *CreateTeam) ProtoReflect() protoreflect.Message {
	mi := &file_domain_teams_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeam.ProtoReflect.Descriptor instead.
func (*CreateTeam) Descriptor() ([]byte, []int) {
	return file_domain_teams_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTeam) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TeamCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *TeamCreated) Reset() {
	*x = TeamCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_teams_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamCreated) ProtoMessage() {}

func (x *TeamCreated) ProtoReflect() protoreflect.Message {
	mi := &file_domain_teams_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamCreated.ProtoReflect.Descriptor instead.
func (*TeamCreated) Descriptor() ([]byte, []int) {
	return file_domain_teams_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TeamCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeamCreated) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type JoinTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *JoinTeam) Reset() {
	*x = JoinTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_teams_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinTeam) ProtoMessage() {}

func (x *JoinTeam) ProtoReflect() protoreflect.Message {
	mi := &file_domain_teams_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinTeam.ProtoReflect.Descriptor instead.
func (*JoinTeam) Descriptor() ([]byte, []int) {
	return file_domain_teams_messages_proto_rawDescGZIP(), []int{2}
}

func (x *JoinTeam) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinTeam) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type TeamJoined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *TeamJoined) Reset() {
	*x = TeamJoined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_teams_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamJoined) ProtoMessage() {}

func (x *TeamJoined) ProtoReflect() protoreflect.Message {
	mi := &file_domain_teams_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamJoined.ProtoReflect.Descriptor instead.
func (*TeamJoined) Descriptor() ([]byte, []int) {
	return file_domain_teams_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TeamJoined) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeamJoined) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type LeaveTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *LeaveTeam) Reset() {
	*x = LeaveTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_teams_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTeam) ProtoMessage() {}

func (x *LeaveTeam) ProtoReflect() protoreflect.Message {
	mi := &file_domain_teams_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTeam.ProtoReflect.Descriptor instead.
func (*LeaveTeam) Descriptor() ([]byte, []int) {
	return file_domain_teams_messages_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveTeam) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TeamLeft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *TeamLeft) Reset() {
	*x = TeamLeft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_teams_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamLeft) ProtoMessage() {}

func (x *TeamLeft) ProtoReflect() protoreflect.Message {
	mi := &file_domain_teams_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamLeft.ProtoReflect.Descriptor instead.
func (*TeamLeft) Descriptor() ([]byte, []int) {
	return file_domain_teams_messages_proto_rawDescGZIP(), []int{5}
}

func (x *TeamLeft) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeamLeft) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type DisbandTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DisbandTeam) Reset() {
	*x = DisbandTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_teams_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisbandTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisbandTeam) ProtoMessage() {}

func (x *DisbandTeam) ProtoReflect() protoreflect.Message {
	mi := &file_domain_teams_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisbandTeam.ProtoReflect.Descriptor instead.
func (*DisbandTeam) Descriptor() ([]byte, []int) {
	return file_domain_teams_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DisbandTeam) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TeamDisbanded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *TeamDisbanded) Reset() {
	*x = TeamDisbanded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_teams_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamDisbanded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamDisbanded) ProtoMessage() {}

func (x *TeamDisbanded) ProtoReflect() protoreflect.Message {
	mi := &file_domain_teams_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamDisbanded.ProtoReflect.Descriptor instead.
func (*TeamDisbanded) Descriptor() ([]byte, []int) {
	return file_domain_teams_messages_proto_rawDescGZIP(), []int{7}
}

func (x *TeamDisbanded) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TeamDisbanded) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

var File_domain_teams_messages_proto protoreflect.FileDescriptor

var file_domain_teams_messages_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x65, 0x61, 0x6d, 0x73, 0x22, 0x25, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x65,
	0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x0b, 0x54,
	0x65, 0x61, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x08,
	0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x0a, 0x54, 0x65,
	0x61, 0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x09, 0x4c, 0x65,
	0x61, 0x76, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x3c, 0x0a, 0x08, 0x54, 0x65, 0x61, 0x6d, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x26,
	0x0a, 0x0b, 0x44, 0x69, 0x73, 0x62, 0x61, 0x6e, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x0d, 0x54, 0x65, 0x61, 0x6d, 0x44, 0x69,
	0x73, 0x62, 0x61, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x78, 0x72, 0x75, 0x64, 0x64,
	0x2f, 0x6c, 0x62, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_domain_teams_messages_proto_rawDescOnce sync.Once
	file_domain_teams_messages_proto_rawDescData = file_domain_teams_messages_proto_rawDesc
)

func file_domain_teams_messages_proto_rawDescGZIP() []byte {
	file_domain_teams_messages_proto_rawDescOnce.Do(func() {
		file_domain_teams_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_teams_messages_proto_rawDescData)
	})
	return file_domain_teams_messages_proto_rawDescData
}

var file_domain_teams_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_domain_teams_messages_proto_goTypes = []interface{}{
	(*CreateTeam)(nil),    // 0: teams.CreateTeam
	(*TeamCreated)(nil),   // 1: teams.TeamCreated
	(*JoinTeam)(nil),      // 2: teams.JoinTeam
	(*TeamJoined)(nil),    // 3: teams.TeamJoined
	(*LeaveTeam)(nil),     // 4: teams.LeaveTeam
	(*TeamLeft)(nil),      // 5: teams.TeamLeft
	(*DisbandTeam)(nil),   // 6: teams.DisbandTeam
	(*TeamDisbanded)(nil), // 7: teams.TeamDisbanded
}
var file_domain_teams_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_teams_messages_proto_init() }
func file_domain_teams_messages_proto_init() {
	if File_domain_teams_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_teams_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_teams_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_teams_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_teams_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamJoined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_teams_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_teams_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamLeft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_teams_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisbandTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_teams_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamDisbanded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_teams_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_teams_messages_proto_goTypes,
		DependencyIndexes: file_domain_teams_messages_proto_depIdxs,
		MessageInfos:      file_domain_teams_messages_proto_msgTypes,
	}.Build()
	File_domain_teams_messages_proto = out.File
	file_domain_teams_messages_proto_rawDesc = nil
	file_domain_teams_messages_proto_goTypes = nil
	file_domain_teams_messages_proto_depIdxs = nil
}
