version: "3.7"

services:
  teams:
    image: teams-svc
    build:
      context: .
    container_name: teams
    restart: on-failure
    depends_on:
      - liftbridge
    ports:
      - 8080:8080

  liftbridge:
    image: liftbridge/standalone-dev
    container_name: liftbridge
    volumes:
      - ./liftbridge.yaml:/liftbridge.yaml
    environment:
      LIFTBRIDGE_HOST: liftbridge
