// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: domain/user/messages.proto

package user

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Invite User to Team
type InviteUserToTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *InviteUserToTeam) Reset() {
	*x = InviteUserToTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_user_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteUserToTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserToTeam) ProtoMessage() {}

func (x *InviteUserToTeam) ProtoReflect() protoreflect.Message {
	mi := &file_domain_user_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserToTeam.ProtoReflect.Descriptor instead.
func (*InviteUserToTeam) Descriptor() ([]byte, []int) {
	return file_domain_user_messages_proto_rawDescGZIP(), []int{0}
}

func (x *InviteUserToTeam) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InviteUserToTeam) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type UserInvitedToTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *UserInvitedToTeam) Reset() {
	*x = UserInvitedToTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_user_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInvitedToTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInvitedToTeam) ProtoMessage() {}

func (x *UserInvitedToTeam) ProtoReflect() protoreflect.Message {
	mi := &file_domain_user_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInvitedToTeam.ProtoReflect.Descriptor instead.
func (*UserInvitedToTeam) Descriptor() ([]byte, []int) {
	return file_domain_user_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UserInvitedToTeam) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInvitedToTeam) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Accept Invite
type AcceptInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *AcceptInvite) Reset() {
	*x = AcceptInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_user_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvite) ProtoMessage() {}

func (x *AcceptInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_user_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvite.ProtoReflect.Descriptor instead.
func (*AcceptInvite) Descriptor() ([]byte, []int) {
	return file_domain_user_messages_proto_rawDescGZIP(), []int{2}
}

func (x *AcceptInvite) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcceptInvite) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type UserAcceptedInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *UserAcceptedInvite) Reset() {
	*x = UserAcceptedInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_user_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAcceptedInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAcceptedInvite) ProtoMessage() {}

func (x *UserAcceptedInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_user_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAcceptedInvite.ProtoReflect.Descriptor instead.
func (*UserAcceptedInvite) Descriptor() ([]byte, []int) {
	return file_domain_user_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UserAcceptedInvite) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAcceptedInvite) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Leave Team
type LeaveTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *LeaveTeam) Reset() {
	*x = LeaveTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_user_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveTeam) ProtoMessage() {}

func (x *LeaveTeam) ProtoReflect() protoreflect.Message {
	mi := &file_domain_user_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveTeam.ProtoReflect.Descriptor instead.
func (*LeaveTeam) Descriptor() ([]byte, []int) {
	return file_domain_user_messages_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveTeam) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserLeftTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *UserLeftTeam) Reset() {
	*x = UserLeftTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_user_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLeftTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeftTeam) ProtoMessage() {}

func (x *UserLeftTeam) ProtoReflect() protoreflect.Message {
	mi := &file_domain_user_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeftTeam.ProtoReflect.Descriptor instead.
func (*UserLeftTeam) Descriptor() ([]byte, []int) {
	return file_domain_user_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UserLeftTeam) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLeftTeam) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Assign Team to User
type AssignTeamToUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *AssignTeamToUser) Reset() {
	*x = AssignTeamToUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_user_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignTeamToUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTeamToUser) ProtoMessage() {}

func (x *AssignTeamToUser) ProtoReflect() protoreflect.Message {
	mi := &file_domain_user_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTeamToUser.ProtoReflect.Descriptor instead.
func (*AssignTeamToUser) Descriptor() ([]byte, []int) {
	return file_domain_user_messages_proto_rawDescGZIP(), []int{6}
}

func (x *AssignTeamToUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignTeamToUser) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type UserAssignedTeam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId string `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *UserAssignedTeam) Reset() {
	*x = UserAssignedTeam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_user_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAssignedTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAssignedTeam) ProtoMessage() {}

func (x *UserAssignedTeam) ProtoReflect() protoreflect.Message {
	mi := &file_domain_user_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAssignedTeam.ProtoReflect.Descriptor instead.
func (*UserAssignedTeam) Descriptor() ([]byte, []int) {
	return file_domain_user_messages_proto_rawDescGZIP(), []int{7}
}

func (x *UserAssignedTeam) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAssignedTeam) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

var File_domain_user_messages_proto protoreflect.FileDescriptor

var file_domain_user_messages_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x44, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x54, 0x6f, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22,
	0x40, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49,
	0x64, 0x22, 0x46, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65,
	0x64, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x09, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x40, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49,
	0x64, 0x22, 0x44, 0x0a, 0x10, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x54, 0x65, 0x61, 0x6d, 0x54,
	0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x42, 0x2a, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x78,
	0x72, 0x75, 0x64, 0x64, 0x2f, 0x6c, 0x62, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_domain_user_messages_proto_rawDescOnce sync.Once
	file_domain_user_messages_proto_rawDescData = file_domain_user_messages_proto_rawDesc
)

func file_domain_user_messages_proto_rawDescGZIP() []byte {
	file_domain_user_messages_proto_rawDescOnce.Do(func() {
		file_domain_user_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_user_messages_proto_rawDescData)
	})
	return file_domain_user_messages_proto_rawDescData
}

var file_domain_user_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_domain_user_messages_proto_goTypes = []interface{}{
	(*InviteUserToTeam)(nil),   // 0: user.InviteUserToTeam
	(*UserInvitedToTeam)(nil),  // 1: user.UserInvitedToTeam
	(*AcceptInvite)(nil),       // 2: user.AcceptInvite
	(*UserAcceptedInvite)(nil), // 3: user.UserAcceptedInvite
	(*LeaveTeam)(nil),          // 4: user.LeaveTeam
	(*UserLeftTeam)(nil),       // 5: user.UserLeftTeam
	(*AssignTeamToUser)(nil),   // 6: user.AssignTeamToUser
	(*UserAssignedTeam)(nil),   // 7: user.UserAssignedTeam
}
var file_domain_user_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_user_messages_proto_init() }
func file_domain_user_messages_proto_init() {
	if File_domain_user_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_user_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteUserToTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_user_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInvitedToTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_user_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_user_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAcceptedInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_user_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_user_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLeftTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_user_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignTeamToUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_user_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAssignedTeam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_user_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_user_messages_proto_goTypes,
		DependencyIndexes: file_domain_user_messages_proto_depIdxs,
		MessageInfos:      file_domain_user_messages_proto_msgTypes,
	}.Build()
	File_domain_user_messages_proto = out.File
	file_domain_user_messages_proto_rawDesc = nil
	file_domain_user_messages_proto_goTypes = nil
	file_domain_user_messages_proto_depIdxs = nil
}
