// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: domain/invite/messages.proto

package invite

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Send
type SendTeamFormationInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviterUserId string `protobuf:"bytes,2,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string `protobuf:"bytes,3,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
}

func (x *SendTeamFormationInvite) Reset() {
	*x = SendTeamFormationInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTeamFormationInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTeamFormationInvite) ProtoMessage() {}

func (x *SendTeamFormationInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTeamFormationInvite.ProtoReflect.Descriptor instead.
func (*SendTeamFormationInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SendTeamFormationInvite) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *SendTeamFormationInvite) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

type TeamFormationInviteSent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,2,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,3,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamFormationInviteSent) Reset() {
	*x = TeamFormationInviteSent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamFormationInviteSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamFormationInviteSent) ProtoMessage() {}

func (x *TeamFormationInviteSent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamFormationInviteSent.ProtoReflect.Descriptor instead.
func (*TeamFormationInviteSent) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TeamFormationInviteSent) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamFormationInviteSent) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamFormationInviteSent) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamFormationInviteSent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Decline
type DeclineTeamFormationInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId string `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
}

func (x *DeclineTeamFormationInvite) Reset() {
	*x = DeclineTeamFormationInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclineTeamFormationInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineTeamFormationInvite) ProtoMessage() {}

func (x *DeclineTeamFormationInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineTeamFormationInvite.ProtoReflect.Descriptor instead.
func (*DeclineTeamFormationInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DeclineTeamFormationInvite) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type TeamFormationInviteDeclined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,2,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,3,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamFormationInviteDeclined) Reset() {
	*x = TeamFormationInviteDeclined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamFormationInviteDeclined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamFormationInviteDeclined) ProtoMessage() {}

func (x *TeamFormationInviteDeclined) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamFormationInviteDeclined.ProtoReflect.Descriptor instead.
func (*TeamFormationInviteDeclined) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{3}
}

func (x *TeamFormationInviteDeclined) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamFormationInviteDeclined) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamFormationInviteDeclined) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamFormationInviteDeclined) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Cancel
type CancelTeamFormationInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId string `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
}

func (x *CancelTeamFormationInvite) Reset() {
	*x = CancelTeamFormationInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTeamFormationInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTeamFormationInvite) ProtoMessage() {}

func (x *CancelTeamFormationInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTeamFormationInvite.ProtoReflect.Descriptor instead.
func (*CancelTeamFormationInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTeamFormationInvite) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type TeamFormationInviteCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,2,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,3,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamFormationInviteCancelled) Reset() {
	*x = TeamFormationInviteCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamFormationInviteCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamFormationInviteCancelled) ProtoMessage() {}

func (x *TeamFormationInviteCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamFormationInviteCancelled.ProtoReflect.Descriptor instead.
func (*TeamFormationInviteCancelled) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{5}
}

func (x *TeamFormationInviteCancelled) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamFormationInviteCancelled) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamFormationInviteCancelled) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamFormationInviteCancelled) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Expire
type ExpireTeamFormationInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId string `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
}

func (x *ExpireTeamFormationInvite) Reset() {
	*x = ExpireTeamFormationInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpireTeamFormationInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireTeamFormationInvite) ProtoMessage() {}

func (x *ExpireTeamFormationInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireTeamFormationInvite.ProtoReflect.Descriptor instead.
func (*ExpireTeamFormationInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ExpireTeamFormationInvite) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type TeamFormationInviteExpired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,2,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,3,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamFormationInviteExpired) Reset() {
	*x = TeamFormationInviteExpired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamFormationInviteExpired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamFormationInviteExpired) ProtoMessage() {}

func (x *TeamFormationInviteExpired) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamFormationInviteExpired.ProtoReflect.Descriptor instead.
func (*TeamFormationInviteExpired) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{7}
}

func (x *TeamFormationInviteExpired) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamFormationInviteExpired) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamFormationInviteExpired) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamFormationInviteExpired) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Accept
type AcceptTeamFormationInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId string `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
}

func (x *AcceptTeamFormationInvite) Reset() {
	*x = AcceptTeamFormationInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptTeamFormationInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptTeamFormationInvite) ProtoMessage() {}

func (x *AcceptTeamFormationInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptTeamFormationInvite.ProtoReflect.Descriptor instead.
func (*AcceptTeamFormationInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptTeamFormationInvite) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type TeamFormationInviteAccepted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,2,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,3,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamFormationInviteAccepted) Reset() {
	*x = TeamFormationInviteAccepted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamFormationInviteAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamFormationInviteAccepted) ProtoMessage() {}

func (x *TeamFormationInviteAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamFormationInviteAccepted.ProtoReflect.Descriptor instead.
func (*TeamFormationInviteAccepted) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{9}
}

func (x *TeamFormationInviteAccepted) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamFormationInviteAccepted) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamFormationInviteAccepted) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamFormationInviteAccepted) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Send
type SendTeamInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId        string `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	InviterUserId string `protobuf:"bytes,2,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string `protobuf:"bytes,3,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
}

func (x *SendTeamInvite) Reset() {
	*x = SendTeamInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTeamInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTeamInvite) ProtoMessage() {}

func (x *SendTeamInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTeamInvite.ProtoReflect.Descriptor instead.
func (*SendTeamInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SendTeamInvite) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SendTeamInvite) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *SendTeamInvite) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

type TeamInviteSent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,3,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,4,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamInviteSent) Reset() {
	*x = TeamInviteSent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamInviteSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamInviteSent) ProtoMessage() {}

func (x *TeamInviteSent) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamInviteSent.ProtoReflect.Descriptor instead.
func (*TeamInviteSent) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{11}
}

func (x *TeamInviteSent) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamInviteSent) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamInviteSent) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamInviteSent) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamInviteSent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Decline
type DeclineTeamInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId string `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
}

func (x *DeclineTeamInvite) Reset() {
	*x = DeclineTeamInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclineTeamInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineTeamInvite) ProtoMessage() {}

func (x *DeclineTeamInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineTeamInvite.ProtoReflect.Descriptor instead.
func (*DeclineTeamInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{12}
}

func (x *DeclineTeamInvite) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type TeamInviteDeclined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,3,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,4,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamInviteDeclined) Reset() {
	*x = TeamInviteDeclined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamInviteDeclined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamInviteDeclined) ProtoMessage() {}

func (x *TeamInviteDeclined) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamInviteDeclined.ProtoReflect.Descriptor instead.
func (*TeamInviteDeclined) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{13}
}

func (x *TeamInviteDeclined) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamInviteDeclined) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamInviteDeclined) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamInviteDeclined) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamInviteDeclined) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Cancel
type CancelTeamInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId string `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
}

func (x *CancelTeamInvite) Reset() {
	*x = CancelTeamInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTeamInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTeamInvite) ProtoMessage() {}

func (x *CancelTeamInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTeamInvite.ProtoReflect.Descriptor instead.
func (*CancelTeamInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{14}
}

func (x *CancelTeamInvite) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type TeamInviteCancelled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,3,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,4,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamInviteCancelled) Reset() {
	*x = TeamInviteCancelled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamInviteCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamInviteCancelled) ProtoMessage() {}

func (x *TeamInviteCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamInviteCancelled.ProtoReflect.Descriptor instead.
func (*TeamInviteCancelled) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{15}
}

func (x *TeamInviteCancelled) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamInviteCancelled) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamInviteCancelled) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamInviteCancelled) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamInviteCancelled) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Expire
type ExpireTeamInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId string `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
}

func (x *ExpireTeamInvite) Reset() {
	*x = ExpireTeamInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpireTeamInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireTeamInvite) ProtoMessage() {}

func (x *ExpireTeamInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireTeamInvite.ProtoReflect.Descriptor instead.
func (*ExpireTeamInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{16}
}

func (x *ExpireTeamInvite) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type TeamInviteExpired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,3,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,4,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamInviteExpired) Reset() {
	*x = TeamInviteExpired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamInviteExpired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamInviteExpired) ProtoMessage() {}

func (x *TeamInviteExpired) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamInviteExpired.ProtoReflect.Descriptor instead.
func (*TeamInviteExpired) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{17}
}

func (x *TeamInviteExpired) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamInviteExpired) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamInviteExpired) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamInviteExpired) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamInviteExpired) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Accept
type AcceptTeamInvite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId string `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
}

func (x *AcceptTeamInvite) Reset() {
	*x = AcceptTeamInvite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptTeamInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptTeamInvite) ProtoMessage() {}

func (x *AcceptTeamInvite) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptTeamInvite.ProtoReflect.Descriptor instead.
func (*AcceptTeamInvite) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{18}
}

func (x *AcceptTeamInvite) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type TeamInviteAccepted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	InviterUserId string                 `protobuf:"bytes,3,opt,name=inviter_user_id,json=inviterUserId,proto3" json:"inviter_user_id,omitempty"`
	InviteeUserId string                 `protobuf:"bytes,4,opt,name=invitee_user_id,json=inviteeUserId,proto3" json:"invitee_user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TeamInviteAccepted) Reset() {
	*x = TeamInviteAccepted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domain_invite_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamInviteAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamInviteAccepted) ProtoMessage() {}

func (x *TeamInviteAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_domain_invite_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamInviteAccepted.ProtoReflect.Descriptor instead.
func (*TeamInviteAccepted) Descriptor() ([]byte, []int) {
	return file_domain_invite_messages_proto_rawDescGZIP(), []int{19}
}

func (x *TeamInviteAccepted) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *TeamInviteAccepted) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *TeamInviteAccepted) GetInviterUserId() string {
	if x != nil {
		return x.InviterUserId
	}
	return ""
}

func (x *TeamInviteAccepted) GetInviteeUserId() string {
	if x != nil {
		return x.InviteeUserId
	}
	return ""
}

func (x *TeamInviteAccepted) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_domain_invite_messages_proto protoreflect.FileDescriptor

var file_domain_invite_messages_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69, 0x0a,
	0x17, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xc0, 0x01, 0x0a, 0x17, 0x54, 0x65, 0x61,
	0x6d, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x53, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49,
	0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x39, 0x0a, 0x1a, 0x44,
	0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x1b, 0x54, 0x65, 0x61, 0x6d, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x44, 0x65,
	0x63, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x38, 0x0a,
	0x19, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x65, 0x61, 0x6d, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0xc5, 0x01, 0x0a, 0x1c, 0x54, 0x65, 0x61, 0x6d,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x38, 0x0a, 0x19, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0xc3, 0x01, 0x0a, 0x1a, 0x54, 0x65,
	0x61, 0x6d, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x38, 0x0a, 0x19, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x1b, 0x54, 0x65,
	0x61, 0x6d, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x79, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xd0, 0x01, 0x0a, 0x0e,
	0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x53, 0x65, 0x6e, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65,
	0x61, 0x6d, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x30,
	0x0a, 0x11, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64,
	0x22, 0xd4, 0x01, 0x0a, 0x12, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x44,
	0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2f, 0x0a, 0x10, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0xd5, 0x01, 0x0a, 0x13, 0x54, 0x65, 0x61,
	0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x2f, 0x0a, 0x10, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49,
	0x64, 0x22, 0xd3, 0x01, 0x0a, 0x11, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2f, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x54, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x22, 0xd4, 0x01, 0x0a, 0x12, 0x54, 0x65, 0x61,
	0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c,
	0x65, 0x78, 0x72, 0x75, 0x64, 0x64, 0x2f, 0x6c, 0x62, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_domain_invite_messages_proto_rawDescOnce sync.Once
	file_domain_invite_messages_proto_rawDescData = file_domain_invite_messages_proto_rawDesc
)

func file_domain_invite_messages_proto_rawDescGZIP() []byte {
	file_domain_invite_messages_proto_rawDescOnce.Do(func() {
		file_domain_invite_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_domain_invite_messages_proto_rawDescData)
	})
	return file_domain_invite_messages_proto_rawDescData
}

var file_domain_invite_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_domain_invite_messages_proto_goTypes = []interface{}{
	(*SendTeamFormationInvite)(nil),      // 0: teams.invite.SendTeamFormationInvite
	(*TeamFormationInviteSent)(nil),      // 1: teams.invite.TeamFormationInviteSent
	(*DeclineTeamFormationInvite)(nil),   // 2: teams.invite.DeclineTeamFormationInvite
	(*TeamFormationInviteDeclined)(nil),  // 3: teams.invite.TeamFormationInviteDeclined
	(*CancelTeamFormationInvite)(nil),    // 4: teams.invite.CancelTeamFormationInvite
	(*TeamFormationInviteCancelled)(nil), // 5: teams.invite.TeamFormationInviteCancelled
	(*ExpireTeamFormationInvite)(nil),    // 6: teams.invite.ExpireTeamFormationInvite
	(*TeamFormationInviteExpired)(nil),   // 7: teams.invite.TeamFormationInviteExpired
	(*AcceptTeamFormationInvite)(nil),    // 8: teams.invite.AcceptTeamFormationInvite
	(*TeamFormationInviteAccepted)(nil),  // 9: teams.invite.TeamFormationInviteAccepted
	(*SendTeamInvite)(nil),               // 10: teams.invite.SendTeamInvite
	(*TeamInviteSent)(nil),               // 11: teams.invite.TeamInviteSent
	(*DeclineTeamInvite)(nil),            // 12: teams.invite.DeclineTeamInvite
	(*TeamInviteDeclined)(nil),           // 13: teams.invite.TeamInviteDeclined
	(*CancelTeamInvite)(nil),             // 14: teams.invite.CancelTeamInvite
	(*TeamInviteCancelled)(nil),          // 15: teams.invite.TeamInviteCancelled
	(*ExpireTeamInvite)(nil),             // 16: teams.invite.ExpireTeamInvite
	(*TeamInviteExpired)(nil),            // 17: teams.invite.TeamInviteExpired
	(*AcceptTeamInvite)(nil),             // 18: teams.invite.AcceptTeamInvite
	(*TeamInviteAccepted)(nil),           // 19: teams.invite.TeamInviteAccepted
	(*timestamppb.Timestamp)(nil),        // 20: google.protobuf.Timestamp
}
var file_domain_invite_messages_proto_depIdxs = []int32{
	20, // 0: teams.invite.TeamFormationInviteSent.timestamp:type_name -> google.protobuf.Timestamp
	20, // 1: teams.invite.TeamFormationInviteDeclined.timestamp:type_name -> google.protobuf.Timestamp
	20, // 2: teams.invite.TeamFormationInviteCancelled.timestamp:type_name -> google.protobuf.Timestamp
	20, // 3: teams.invite.TeamFormationInviteExpired.timestamp:type_name -> google.protobuf.Timestamp
	20, // 4: teams.invite.TeamFormationInviteAccepted.timestamp:type_name -> google.protobuf.Timestamp
	20, // 5: teams.invite.TeamInviteSent.timestamp:type_name -> google.protobuf.Timestamp
	20, // 6: teams.invite.TeamInviteDeclined.timestamp:type_name -> google.protobuf.Timestamp
	20, // 7: teams.invite.TeamInviteCancelled.timestamp:type_name -> google.protobuf.Timestamp
	20, // 8: teams.invite.TeamInviteExpired.timestamp:type_name -> google.protobuf.Timestamp
	20, // 9: teams.invite.TeamInviteAccepted.timestamp:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_domain_invite_messages_proto_init() }
func file_domain_invite_messages_proto_init() {
	if File_domain_invite_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_domain_invite_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTeamFormationInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamFormationInviteSent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclineTeamFormationInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamFormationInviteDeclined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTeamFormationInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamFormationInviteCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpireTeamFormationInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamFormationInviteExpired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptTeamFormationInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamFormationInviteAccepted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTeamInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamInviteSent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclineTeamInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamInviteDeclined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTeamInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamInviteCancelled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpireTeamInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamInviteExpired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptTeamInvite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domain_invite_messages_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamInviteAccepted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domain_invite_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_invite_messages_proto_goTypes,
		DependencyIndexes: file_domain_invite_messages_proto_depIdxs,
		MessageInfos:      file_domain_invite_messages_proto_msgTypes,
	}.Build()
	File_domain_invite_messages_proto = out.File
	file_domain_invite_messages_proto_rawDesc = nil
	file_domain_invite_messages_proto_goTypes = nil
	file_domain_invite_messages_proto_depIdxs = nil
}
